apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-z
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-z
  template:
    metadata:
      labels:
        app: project-z
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-pro-claim

      containers:
        - name: project-beta
          image: "balajistark/projectbeta:2.0.0"
          volumeMounts:
            - mountPath: "/app/db"
              name: pv-storage
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
        - name: sqlite
          image: "sqlite:1.0"
          volumeMounts:
            - mountPath: "/app/db"
              name: pv-storage
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5008

---
apiVersion: v1
kind: Service
metadata:
  name: pro-service
spec:
  selector:
    app: project-z
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
  type: LoadBalancer
